openapi: 3.1.0
info:
  title: Penn Academic Planner Retrieval API
  description: >
    This API supports academic course planning by allowing Penn students to query and filter
    documents (including programs, courses, and related attributes) using natural language queries
    and detailed metadata filters. Results are aggregated across multiple collections.
  version: 1.0.0
servers:
  - url: https://chatgpt-retrieval-plugin-9phi.onrender.com
paths:
  /query:
    post:
      summary: Search for Academic Information
      description: >
        Accepts an array of query objects—each with a query string, an optional metadata filter,
        and custom top_k values—to aggregate results from all collections using the specified parameters.
      operationId: query_query_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryRequest"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
components:
  schemas:
    ChinguDocumentChunkMetadata:
      title: ChinguDocumentChunkMetadata
      type: object
      properties:
        doc_type:
          title: Doc Type (e.g., course, attribute, program)
          type: string
        course_code:
          title: Course Code
          type: string
        course_title:
          title: Course Title
          type: string
        course_unit:
          title: Course Unit
          type: string
        term:
          title: Term (e.g., Fall 2023, Spring 2024)
          type: string
        attribute:
          title: Attribute
          type: string
        program_url:
          title: Program URL
          type: string
        academic_level:
          title: Academic Level
          type: string
        school:
          title: School
          type: string
        format:
          title: Format (On-Campus, Online/Hybrid)
          type: string
        major_minor:
          title: Major/Minor (Major, Minor)
          type: string
        degree:
          title: Degree
          type: string
        requirements:
          title: Requirements (e.g., courses needed)
          type: string
        subject_url:
          title: Subject URL
          type: string
        course_code_no:
          title: Course Code Number
          type: integer
        instructor:
          title: Instructor (First name initial, period, space, then last name)
          type: string
        source:
          title: Source
          type: string
    DocumentMetadataFilter:
      title: DocumentMetadataFilter
      type: object
      properties:
        document_id:
          title: Document ID
          type: string
        source:
          $ref: "#/components/schemas/Source"
        source_id:
          title: Source ID
          type: string
        author:
          title: Author
          type: string
        start_date:
          title: Start Date
          type: string
          format: date-time
        end_date:
          title: End Date
          type: string
          format: date-time
        doc_type:
          title: Doc Type (e.g., course, attribute, program)
          type: string
        course_code:
          title: Course Code
          type: string
        course_title:
          title: Course Title
          type: string
        course_unit:
          title: Course Unit
          type: string
        term:
          title: Term (e.g., Fall 2023, Spring 2024)
          type: string
        attribute:
          title: Attribute
          type: string
        program_url:
          title: Program URL
          type: string
        academic_level:
          title: Academic Level
          type: string
        school:
          title: School
          type: string
        format:
          title: Format
          type: string
        major_minor:
          title: Major/Minor
          type: string
        degree:
          title: Degree
          type: string
        requirements:
          title: Requirements
          type: string
        subject_url:
          title: Subject URL
          type: string
        course_code_no:
          title: Course Code Number
          type: integer
        instructor:
          title: Instructor (First name initial, period, space, then last name)
          type: string
    Source:
      title: Source
      type: string
      enum:
        - email
        - file
        - chat
        - programs
        - courses
        - attributes_flat
        - attributes_grouped
        - courses_term
    ValidationError:
      title: ValidationError
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    QueryInput:
      title: QueryInput
      type: object
      description: >
        The input query model. If any of the top_k fields are omitted or set to 0, defaults are applied:
        top_k defaults to 5, top_k_programs to 3, top_k_courses to 7, and top_k_attributes to 5.
      required:
        - query
      properties:
        query:
          title: Query
          type: string
        filter:
          $ref: "#/components/schemas/DocumentMetadataFilter"
        top_k:
          title: Top K (Fallback for collections without a dedicated value)
          type: integer
          default: 5
        top_k_programs:
          title: Top K for Programs
          type: integer
          default: 3
        top_k_courses:
          title: Top K for Courses
          type: integer
          default: 10
        top_k_attributes:
          title: Top K for Attributes
          type: integer
          default: 7
    QueryRequest:
      title: QueryRequest
      type: object
      required:
        - queries
      properties:
        queries:
          title: Queries
          type: array
          items:
            $ref: "#/components/schemas/QueryInput"
    QueryResult:
      title: QueryResult
      type: object
      required:
        - query
        - results
      properties:
        query:
          title: Query
          type: string
        results:
          title: Results
          type: array
          items:
            $ref: "#/components/schemas/DocumentChunkWithScore"
    DocumentChunkWithScore:
      title: DocumentChunkWithScore
      type: object
      required:
        - text
        - metadata
        - score
      properties:
        id:
          title: ID
          type: string
        text:
          title: Text
          type: string
        metadata:
          $ref: "#/components/schemas/ChinguDocumentChunkMetadata"
        embedding:
          title: Embedding
          type: array
          items:
            type: number
        score:
          title: Score
          type: number
    QueryResponse:
      title: QueryResponse
      type: object
      required:
        - results
      properties:
        results:
          title: Results
          type: array
          items:
            $ref: "#/components/schemas/QueryResult"
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer